const SINGLE_USER_REQUEST = '@users/SINGLE_USER_REQUEST';
const SINGLE_USER_SUCCESS = '@users/SINGLE_USER_SUCCESS';
const SINGLE_USER_FAILURE = '@users/SINGLE_USER_FAILURE';

export default {
  SINGLE_USER_REQUEST,
  SINGLE_USER_SUCCESS,
  SINGLE_USER_FAILURE,
};
