const USERS_REQUEST = '@users/USERS_REQUEST';
const USERS_SUCCESS = '@users/USERS_SUCCESS';
const USERS_FAILURE = '@users/USERS_FAILURE';

export default {
  USERS_REQUEST,
  USERS_SUCCESS,
  USERS_FAILURE,
};
