const USERS_REQUEST = '@users/LOGIN_REQUEST';
const USERS_SUCCESS = '@users/LOGIN_SUCCESS';
const USERS_FAILURE = '@users/LOGIN_FAILURE';

export default {
  USERS_REQUEST,
  USERS_SUCCESS,
  USERS_FAILURE,
};
