const USERS_RECORDS_REQUEST = '@users/USERS_RECORDS_REQUEST';
const USERS_RECORDS_SUCCESS = '@users/USERS_RECORDS_SUCCESS';
const USERS_RECORDS_FAILURE = '@users/USERS_RECORDS_FAILURE';

export default {
  USERS_RECORDS_REQUEST,
  USERS_RECORDS_SUCCESS,
  USERS_RECORDS_FAILURE,
};
