const LOGIN_REQUEST = '@user/LOGIN_REQUEST';
const LOGIN_SUCCESS = '@user/LOGIN_SUCCESS';
const LOGIN_FAILURE = '@user/LOGIN_FAILURE';
const REGISTER_REQUEST = '@user/REGISTER_REQUEST';
const REGISTER_SUCCESS = '@user/REGISTER_SUCCESS';
const REGISTER_FAILURE = '@user/REGISTER_FAILURE';
const EDIT_USER_REQUEST = '@user/EDIT_USER_REQUEST';
const EDIT_USER_SUCCESS = '@user/EDIT_USER_SUCCESS';
const EDIT_USER_FAILURE = '@user/EDIT_USER_FAILURE';
const FETCH_CURRENT_USER_REQUEST = '@user/FETCH_CURRENT_USER_REQUEST';
const FETCH_CURRENT_USER_SUCCESS = '@user/FETCH_CURRENT_USER_SUCCESS';
const FETCH_CURRENT_USER_FAILURE = '@user/FETCH_CURRENT_USER_FAILURE';

export default {
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  EDIT_USER_REQUEST,
  EDIT_USER_SUCCESS,
  EDIT_USER_FAILURE,
  FETCH_CURRENT_USER_REQUEST,
  FETCH_CURRENT_USER_SUCCESS,
  FETCH_CURRENT_USER_FAILURE,
};
