const LOGIN_REQUEST = '@user/LOGIN_REQUEST';
const LOGIN_SUCCESS = '@user/LOGIN_SUCCESS';
const LOGIN_FAILURE = '@user/LOGIN_FAILURE';
const REGISTER_REQUEST = '@user/REGISTER_REQUEST';
const REGISTER_SUCCESS = '@user/REGISTER_SUCCESS';
const REGISTER_FAILURE = '@user/REGISTER_FAILURE';

export default {
  REGISTER_REQUEST,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
};
