const FETCH_ALL_EXCERCISES_REQUEST = '@excercises/FETCH_ALL_EXCERCISES_REQUEST';
const FETCH_ALL_EXCERCISES_SUCCESS = '@excercises/FETCH_ALL_EXCERCISES_SUCCESS';
const FETCH_ALL_EXCERCISES_FAILURE = '@excercises/FETCH_ALL_EXCERCISES_FAILURE';

export default {
  FETCH_ALL_EXCERCISES_REQUEST,
  FETCH_ALL_EXCERCISES_SUCCESS,
  FETCH_ALL_EXCERCISES_FAILURE,
};
