const FETCH_ALL_EXCERCISES_REQUEST = '@excercises/FETCH_ALL_EXCERCISES_REQUEST';
const FETCH_ALL_EXCERCISES_SUCCESS = '@excercises/FETCH_ALL_EXCERCISES_SUCCESS';
const FETCH_ALL_EXCERCISES_FAILURE = '@excercises/FETCH_ALL_EXCERCISES_FAILURE';

const FETCH_ALL_WORKOUTS_REQUEST = '@excercises/FETCH_ALL_WORKOUTS_REQUEST';
const FETCH_ALL_WORKOUTS_SUCCESS = '@excercises/FETCH_ALL_WORKOUTS_SUCCESS';
const FETCH_ALL_WORKOUTS_FAILURE = '@excercises/FETCH_ALL_WORKOUTS_FAILURE';

const ADD_TRAINING_REQUEST = '@excercises/ADD_TRAINING_REQUEST';
const ADD_TRAINING_SUCCESS = '@excercises/ADD_TRAINING_SUCCESS';
const ADD_TRAINING_FAILURE = '@excercises/ADD_TRAINING_FAILURE';

export default {
  FETCH_ALL_EXCERCISES_REQUEST,
  FETCH_ALL_EXCERCISES_SUCCESS,
  FETCH_ALL_EXCERCISES_FAILURE,
  ADD_TRAINING_REQUEST,
  ADD_TRAINING_SUCCESS,
  ADD_TRAINING_FAILURE,
  FETCH_ALL_WORKOUTS_REQUEST,
  FETCH_ALL_WORKOUTS_SUCCESS,
  FETCH_ALL_WORKOUTS_FAILURE,
};
