const FETCH_ALL_EXCERCISES_REQUEST = '@excercises/FETCH_ALL_EXCERCISES_REQUEST';
const FETCH_ALL_EXCERCISES_SUCCESS = '@excercises/FETCH_ALL_EXCERCISES_SUCCESS';
const FETCH_ALL_EXCERCISES_FAILURE = '@excercises/FETCH_ALL_EXCERCISES_FAILURE';

const FETCH_ALL_WORKOUTS_REQUEST = '@excercises/FETCH_ALL_WORKOUTS_REQUEST';
const FETCH_ALL_WORKOUTS_SUCCESS = '@excercises/FETCH_ALL_WORKOUTS_SUCCESS';
const FETCH_ALL_WORKOUTS_FAILURE = '@excercises/FETCH_ALL_WORKOUTS_FAILURE';

const ADD_WORKOUT_REQUEST = '@excercises/ADD_WORKOUT_REQUEST';
const ADD_WORKOUT_SUCCESS = '@excercises/ADD_WORKOUT_SUCCESS';
const ADD_WORKOUT_FAILURE = '@excercises/ADD_WORKOUT_FAILURE';

const UPDATE_WORKOUT_PLAN_REQUEST = '@excercises/UPDATE_WORKOUT_PLAN_REQUEST';
const UPDATE_WORKOUT_PLAN_SUCCESS = '@excercises/UPDATE_WORKOUT_PLAN_SUCCESS';
const UPDATE_WORKOUT_PLAN_FAILURE = '@excercises/UPDATE_WORKOUT_PLAN_FAILURE';

export default {
  FETCH_ALL_EXCERCISES_REQUEST,
  FETCH_ALL_EXCERCISES_SUCCESS,
  FETCH_ALL_EXCERCISES_FAILURE,
  ADD_WORKOUT_REQUEST,
  ADD_WORKOUT_SUCCESS,
  ADD_WORKOUT_FAILURE,
  FETCH_ALL_WORKOUTS_REQUEST,
  FETCH_ALL_WORKOUTS_SUCCESS,
  FETCH_ALL_WORKOUTS_FAILURE,
  UPDATE_WORKOUT_PLAN_REQUEST,
  UPDATE_WORKOUT_PLAN_SUCCESS,
  UPDATE_WORKOUT_PLAN_FAILURE,
};
